export const DRIVER_DETAILS = {
 driverDetails: [
    {
      driverType: "Primary",
      checkScore: 80.0,
      checkPerformedby: "Stripe",
      checkPerformedDate: "2022-07-13",
      eligibilityCategory: "Car",
      subCategory: "WG/AO",
      issuingAuthority: "RTO Bangalore",
      eligibility: "A/B/L",
      driverStatus: "Active",
      expiryDate: "2050-07-13",
      issuingDate: "2020-01-01",
      issuingCountry: "a0H5i00000CXFvFEAX",
      driverLastName: "Mustermann",
      driverFristName: "Max",
      licenseNumber: "H012MH2122",
      driverId: "a4rfwrert876001",
      driverLicenseStatus: "Verified",
      driverStartDate: "2023-08-22",
      driverEndDate: "2023-08-23",
    },
    {
      driverType: "Primary",
      checkScore: 80.0,
      checkPerformedby: "Stripe",
      checkPerformedDate: "2022-07-13",
      eligibilityCategory: "Car",
      subCategory: "WG/AO",
      issuingAuthority: "RTO Bangalore",
      eligibility: "A/B/L",
      driverStatus: "Active",
      expiryDate: "2050-07-13",
      issuingDate: "2020-01-01",
      issuingCountry: "a0H5i00000CXFvFEAX",
      driverLastName: "Email",
      driverFristName: "Test",
      licenseNumber: "H012MH2122",
      driverId: "a4rfwrert876002",
      driverLicenseStatus: "Verified",
      driverStartDate: "2023-08-17",
      driverEndDate: "2023-08-23",
    },
    {
      driverType: "Secondary",
      checkScore: 80.0,
      checkPerformedby: "Stripe",
      checkPerformedDate: "2022-07-13",
      eligibilityCategory: "Car",
      subCategory: "WG/AO",
      issuingAuthority: "RTO Bangalore",
      eligibility: "A/B/L",
      driverStatus: "Active",
      expiryDate: "2050-07-13",
      issuingDate: "2020-01-01",
      issuingCountry: "a0H5i00000CXFvFEAX",
      driverLastName: "Email",
      driverFristName: "Test2",
      licenseNumber: "H012MH2122",
      driverId: "a4rfwrert876003",
      driverLicenseStatus: "Verified",
      driverStartDate: "2023-08-18",
      driverEndDate: "2023-08-23",
    }
  ]
}